/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 14.1 		*/
/*  Created On : 31-déc.-2025 00:42:59 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */
SET FOREIGN_KEY_CHECKS=0;

-- Suppression des tables existantes
DROP TABLE IF EXISTS `ArchivesUser` CASCADE;
DROP TABLE IF EXISTS `Fileinformation` CASCADE;
DROP TABLE IF EXISTS `User` CASCADE;
DROP TABLE IF EXISTS `Archives` CASCADE;
DROP TABLE IF EXISTS `Account` CASCADE;

-- Création des tables

CREATE TABLE `Account`
(
    `AccountID` INT NOT NULL AUTO_INCREMENT,
    `Email` varchar(255) NOT NULL,
    `Password` varchar(255) NOT NULL,
    CONSTRAINT `PK_Account` PRIMARY KEY (`AccountID` ASC)
);

CREATE TABLE `Archives`
(
    `ArchivesID` INT NOT NULL AUTO_INCREMENT,
    CONSTRAINT `PK_Archives` PRIMARY KEY (`ArchivesID` ASC)
);

CREATE TABLE `User`
(
    `UserID` INT NOT NULL AUTO_INCREMENT,
    `Dateofbirth` DATE NOT NULL,
    `Firstname` varchar(255) NOT NULL,
    `Gender` varchar(255) NOT NULL,
    `Lastname` varchar(255) NOT NULL,
    `AccountID` INT NOT NULL,
    CONSTRAINT `PK_User` PRIMARY KEY (`UserID` ASC)
);

CREATE TABLE `ArchivesUser`
(
    `UserID` INT NOT NULL,
    `ArchivesID` INT NOT NULL
);

CREATE TABLE `Fileinformation`
(
    `FileinformationID` INT NOT NULL AUTO_INCREMENT,
    `Extension` varchar(255) NOT NULL,
    `Filename` varchar(255) NOT NULL,
    `Filepath` varchar(255) NOT NULL,
    `Lastmodification` DATE NOT NULL,
    `ArchivesID` INT NOT NULL,
    CONSTRAINT `PK_Fileinformation` PRIMARY KEY (`FileinformationID` ASC)
);

CREATE TABLE `FilePairs`
(
    `FilePairID` INT NOT NULL AUTO_INCREMENT,
    `LastModified` DATE NOT NULL,
    `ArchivesID` INT NOT NULL,
    `XmlFileID` INT NULL,
    `JsonFileID` INT NULL,
    CONSTRAINT `PK_FilePairs` PRIMARY KEY (`FilePairID` ASC)
);

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `Account` 
 ADD CONSTRAINT `email_unique` UNIQUE (`Email` ASC)
;

-- Création des clés étrangères

ALTER TABLE `User` 
 ADD CONSTRAINT `FK_User_Account`
    FOREIGN KEY (`AccountID`) REFERENCES `Account` (`AccountID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `ArchivesUser` 
 ADD CONSTRAINT `FK_ArchivesUser_User`
    FOREIGN KEY (`UserID`) REFERENCES `User` (`UserID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `ArchivesUser` 
 ADD CONSTRAINT `FK_ArchivesUser_Archives`
    FOREIGN KEY (`ArchivesID`) REFERENCES `Archives` (`ArchivesID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `Fileinformation` 
 ADD CONSTRAINT `FK_Fileinformation_Archives`
    FOREIGN KEY (`ArchivesID`) REFERENCES `Archives` (`ArchivesID`) ON DELETE NO ACTION ON UPDATE NO ACTION;
    
ALTER TABLE `FilePairs` 
 ADD CONSTRAINT `FK_FilePairs_Archives`
    FOREIGN KEY (`ArchivesID`) REFERENCES `Archives` (`ArchivesID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
 ADD CONSTRAINT `FK_FilePairs_XmlFile`
    FOREIGN KEY (`XmlFileID`) REFERENCES `Fileinformation` (`FileinformationID`) ON DELETE SET NULL ON UPDATE CASCADE,
 ADD CONSTRAINT `FK_FilePairs_JsonFile`
    FOREIGN KEY (`JsonFileID`) REFERENCES `Fileinformation` (`FileinformationID`) ON DELETE SET NULL ON UPDATE CASCADE;

SET FOREIGN_KEY_CHECKS=1;

